### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by bomholmm** [alex030/UserConfigAgent#1]
Not sure what I'm doing wrong but I can't get the install pkg built.

I keep getting a certificate related error.

"Check dependencies
No certificate matching '3rd Party Mac Developer Application: Computacenter AG & Co. oHG (3E28GJFZZ4)':  Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning."

Could you put the .pkg up as a release?

**Comment by alex030** [comment]
Hi, you need to change your signing certificate in all the three targets in the Xcode project. Sorry for that.
<img width="915" alt="bildschirmfoto 2016-10-25 um 10 41 32" src="https://cloud.githubusercontent.com/assets/1160611/19678861/d6c5d8e0-9a9f-11e6-8d82-e9203740d542.png">
